/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.sample.atm.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ATMElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.atm.Dsl.ATM");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cATMAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cATMKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAtmIDKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cAtmIDAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cAtmIDEStringParserRuleCall_3_1_0 = (RuleCall)cAtmIDAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAddressKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAddressAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAddressEStringParserRuleCall_4_1_0 = (RuleCall)cAddressAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ATM returns ATM:
		//    {ATM}
		//    'ATM'
		//    '{'
		//        ('atmID' atmID=EString)?
		//        ('address' address=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ATM}
		//'ATM'
		//'{'
		//    ('atmID' atmID=EString)?
		//    ('address' address=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{ATM}
		public Action getATMAction_0() { return cATMAction_0; }
		
		//'ATM'
		public Keyword getATMKeyword_1() { return cATMKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('atmID' atmID=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'atmID'
		public Keyword getAtmIDKeyword_3_0() { return cAtmIDKeyword_3_0; }
		
		//atmID=EString
		public Assignment getAtmIDAssignment_3_1() { return cAtmIDAssignment_3_1; }
		
		//EString
		public RuleCall getAtmIDEStringParserRuleCall_3_1_0() { return cAtmIDEStringParserRuleCall_3_1_0; }
		
		//('address' address=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'address'
		public Keyword getAddressKeyword_4_0() { return cAddressKeyword_4_0; }
		
		//address=EString
		public Assignment getAddressAssignment_4_1() { return cAddressAssignment_4_1; }
		
		//EString
		public RuleCall getAddressEStringParserRuleCall_4_1_0() { return cAddressEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.atm.Dsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class BankClerkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.atm.Dsl.BankClerk");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBankClerkAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBankClerkKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cUserIDAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cUserIDEStringParserRuleCall_2_0 = (RuleCall)cUserIDAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_4_1_0 = (RuleCall)cNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAddressKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAddressAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAddressEStringParserRuleCall_5_1_0 = (RuleCall)cAddressAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAgeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cAgeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cAgeEStringParserRuleCall_6_1_0 = (RuleCall)cAgeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPhoneKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPhoneAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPhoneEStringParserRuleCall_7_1_0 = (RuleCall)cPhoneAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cPostKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cPostAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cPostEStringParserRuleCall_8_1_0 = (RuleCall)cPostAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cPinKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cPinAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cPinEStringParserRuleCall_9_1_0 = (RuleCall)cPinAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cUesr2bankKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cUesr2bankAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cUesr2bankBankCrossReference_10_1_0 = (CrossReference)cUesr2bankAssignment_10_1.eContents().get(0);
		private final RuleCall cUesr2bankBankEStringParserRuleCall_10_1_0_1 = (RuleCall)cUesr2bankBankCrossReference_10_1_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cAtmUserKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cAtmUserAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cAtmUserATMCrossReference_11_1_0 = (CrossReference)cAtmUserAssignment_11_1.eContents().get(0);
		private final RuleCall cAtmUserATMEStringParserRuleCall_11_1_0_1 = (RuleCall)cAtmUserATMCrossReference_11_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//BankClerk returns BankClerk:
		//    {BankClerk}
		//    'BankClerk'
		//    userID=EString
		//    '{'
		//        ('name' name=EString)?
		//        ('address' address=EString)?
		//        ('age' age=EString)?
		//        ('phone' phone=EString)?
		//        ('Post' Post=EString)?
		//        ('pin' pin=EString)?
		//        ('uesr2bank' uesr2bank=[Bank|EString])?
		//        ('atmUser' atmUser=[ATM|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{BankClerk}
		//'BankClerk'
		//userID=EString
		//'{'
		//    ('name' name=EString)?
		//    ('address' address=EString)?
		//    ('age' age=EString)?
		//    ('phone' phone=EString)?
		//    ('Post' Post=EString)?
		//    ('pin' pin=EString)?
		//    ('uesr2bank' uesr2bank=[Bank|EString])?
		//    ('atmUser' atmUser=[ATM|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{BankClerk}
		public Action getBankClerkAction_0() { return cBankClerkAction_0; }
		
		//'BankClerk'
		public Keyword getBankClerkKeyword_1() { return cBankClerkKeyword_1; }
		
		//userID=EString
		public Assignment getUserIDAssignment_2() { return cUserIDAssignment_2; }
		
		//EString
		public RuleCall getUserIDEStringParserRuleCall_2_0() { return cUserIDEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('name' name=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'name'
		public Keyword getNameKeyword_4_0() { return cNameKeyword_4_0; }
		
		//name=EString
		public Assignment getNameAssignment_4_1() { return cNameAssignment_4_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_4_1_0() { return cNameEStringParserRuleCall_4_1_0; }
		
		//('address' address=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'address'
		public Keyword getAddressKeyword_5_0() { return cAddressKeyword_5_0; }
		
		//address=EString
		public Assignment getAddressAssignment_5_1() { return cAddressAssignment_5_1; }
		
		//EString
		public RuleCall getAddressEStringParserRuleCall_5_1_0() { return cAddressEStringParserRuleCall_5_1_0; }
		
		//('age' age=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'age'
		public Keyword getAgeKeyword_6_0() { return cAgeKeyword_6_0; }
		
		//age=EString
		public Assignment getAgeAssignment_6_1() { return cAgeAssignment_6_1; }
		
		//EString
		public RuleCall getAgeEStringParserRuleCall_6_1_0() { return cAgeEStringParserRuleCall_6_1_0; }
		
		//('phone' phone=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'phone'
		public Keyword getPhoneKeyword_7_0() { return cPhoneKeyword_7_0; }
		
		//phone=EString
		public Assignment getPhoneAssignment_7_1() { return cPhoneAssignment_7_1; }
		
		//EString
		public RuleCall getPhoneEStringParserRuleCall_7_1_0() { return cPhoneEStringParserRuleCall_7_1_0; }
		
		//('Post' Post=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'Post'
		public Keyword getPostKeyword_8_0() { return cPostKeyword_8_0; }
		
		//Post=EString
		public Assignment getPostAssignment_8_1() { return cPostAssignment_8_1; }
		
		//EString
		public RuleCall getPostEStringParserRuleCall_8_1_0() { return cPostEStringParserRuleCall_8_1_0; }
		
		//('pin' pin=EString)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'pin'
		public Keyword getPinKeyword_9_0() { return cPinKeyword_9_0; }
		
		//pin=EString
		public Assignment getPinAssignment_9_1() { return cPinAssignment_9_1; }
		
		//EString
		public RuleCall getPinEStringParserRuleCall_9_1_0() { return cPinEStringParserRuleCall_9_1_0; }
		
		//('uesr2bank' uesr2bank=[Bank|EString])?
		public Group getGroup_10() { return cGroup_10; }
		
		//'uesr2bank'
		public Keyword getUesr2bankKeyword_10_0() { return cUesr2bankKeyword_10_0; }
		
		//uesr2bank=[Bank|EString]
		public Assignment getUesr2bankAssignment_10_1() { return cUesr2bankAssignment_10_1; }
		
		//[Bank|EString]
		public CrossReference getUesr2bankBankCrossReference_10_1_0() { return cUesr2bankBankCrossReference_10_1_0; }
		
		//EString
		public RuleCall getUesr2bankBankEStringParserRuleCall_10_1_0_1() { return cUesr2bankBankEStringParserRuleCall_10_1_0_1; }
		
		//('atmUser' atmUser=[ATM|EString])?
		public Group getGroup_11() { return cGroup_11; }
		
		//'atmUser'
		public Keyword getAtmUserKeyword_11_0() { return cAtmUserKeyword_11_0; }
		
		//atmUser=[ATM|EString]
		public Assignment getAtmUserAssignment_11_1() { return cAtmUserAssignment_11_1; }
		
		//[ATM|EString]
		public CrossReference getAtmUserATMCrossReference_11_1_0() { return cAtmUserATMCrossReference_11_1_0; }
		
		//EString
		public RuleCall getAtmUserATMEStringParserRuleCall_11_1_0_1() { return cAtmUserATMEStringParserRuleCall_11_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class CustomerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.atm.Dsl.Customer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCustomerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCustomerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cUserIDAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cUserIDEStringParserRuleCall_2_0 = (RuleCall)cUserIDAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_4_1_0 = (RuleCall)cNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAddressKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAddressAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAddressEStringParserRuleCall_5_1_0 = (RuleCall)cAddressAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAgeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cAgeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cAgeEStringParserRuleCall_6_1_0 = (RuleCall)cAgeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPhoneKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPhoneAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPhoneEStringParserRuleCall_7_1_0 = (RuleCall)cPhoneAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cUesr2bankKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cUesr2bankAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cUesr2bankBankCrossReference_8_1_0 = (CrossReference)cUesr2bankAssignment_8_1.eContents().get(0);
		private final RuleCall cUesr2bankBankEStringParserRuleCall_8_1_0_1 = (RuleCall)cUesr2bankBankCrossReference_8_1_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cAtmUserKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cAtmUserAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cAtmUserATMCrossReference_9_1_0 = (CrossReference)cAtmUserAssignment_9_1.eContents().get(0);
		private final RuleCall cAtmUserATMEStringParserRuleCall_9_1_0_1 = (RuleCall)cAtmUserATMCrossReference_9_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Customer returns Customer:
		//    {Customer}
		//    'Customer'
		//    userID=EString
		//    '{'
		//        ('name' name=EString)?
		//        ('address' address=EString)?
		//        ('age' age=EString)?
		//        ('phone' phone=EString)?
		//        ('uesr2bank' uesr2bank=[Bank|EString])?
		//        ('atmUser' atmUser=[ATM|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Customer}
		//'Customer'
		//userID=EString
		//'{'
		//    ('name' name=EString)?
		//    ('address' address=EString)?
		//    ('age' age=EString)?
		//    ('phone' phone=EString)?
		//    ('uesr2bank' uesr2bank=[Bank|EString])?
		//    ('atmUser' atmUser=[ATM|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Customer}
		public Action getCustomerAction_0() { return cCustomerAction_0; }
		
		//'Customer'
		public Keyword getCustomerKeyword_1() { return cCustomerKeyword_1; }
		
		//userID=EString
		public Assignment getUserIDAssignment_2() { return cUserIDAssignment_2; }
		
		//EString
		public RuleCall getUserIDEStringParserRuleCall_2_0() { return cUserIDEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('name' name=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'name'
		public Keyword getNameKeyword_4_0() { return cNameKeyword_4_0; }
		
		//name=EString
		public Assignment getNameAssignment_4_1() { return cNameAssignment_4_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_4_1_0() { return cNameEStringParserRuleCall_4_1_0; }
		
		//('address' address=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'address'
		public Keyword getAddressKeyword_5_0() { return cAddressKeyword_5_0; }
		
		//address=EString
		public Assignment getAddressAssignment_5_1() { return cAddressAssignment_5_1; }
		
		//EString
		public RuleCall getAddressEStringParserRuleCall_5_1_0() { return cAddressEStringParserRuleCall_5_1_0; }
		
		//('age' age=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'age'
		public Keyword getAgeKeyword_6_0() { return cAgeKeyword_6_0; }
		
		//age=EString
		public Assignment getAgeAssignment_6_1() { return cAgeAssignment_6_1; }
		
		//EString
		public RuleCall getAgeEStringParserRuleCall_6_1_0() { return cAgeEStringParserRuleCall_6_1_0; }
		
		//('phone' phone=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'phone'
		public Keyword getPhoneKeyword_7_0() { return cPhoneKeyword_7_0; }
		
		//phone=EString
		public Assignment getPhoneAssignment_7_1() { return cPhoneAssignment_7_1; }
		
		//EString
		public RuleCall getPhoneEStringParserRuleCall_7_1_0() { return cPhoneEStringParserRuleCall_7_1_0; }
		
		//('uesr2bank' uesr2bank=[Bank|EString])?
		public Group getGroup_8() { return cGroup_8; }
		
		//'uesr2bank'
		public Keyword getUesr2bankKeyword_8_0() { return cUesr2bankKeyword_8_0; }
		
		//uesr2bank=[Bank|EString]
		public Assignment getUesr2bankAssignment_8_1() { return cUesr2bankAssignment_8_1; }
		
		//[Bank|EString]
		public CrossReference getUesr2bankBankCrossReference_8_1_0() { return cUesr2bankBankCrossReference_8_1_0; }
		
		//EString
		public RuleCall getUesr2bankBankEStringParserRuleCall_8_1_0_1() { return cUesr2bankBankEStringParserRuleCall_8_1_0_1; }
		
		//('atmUser' atmUser=[ATM|EString])?
		public Group getGroup_9() { return cGroup_9; }
		
		//'atmUser'
		public Keyword getAtmUserKeyword_9_0() { return cAtmUserKeyword_9_0; }
		
		//atmUser=[ATM|EString]
		public Assignment getAtmUserAssignment_9_1() { return cAtmUserAssignment_9_1; }
		
		//[ATM|EString]
		public CrossReference getAtmUserATMCrossReference_9_1_0() { return cAtmUserATMCrossReference_9_1_0; }
		
		//EString
		public RuleCall getAtmUserATMEStringParserRuleCall_9_1_0_1() { return cAtmUserATMEStringParserRuleCall_9_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class BankCardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.atm.Dsl.BankCard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBankCardAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBankCardKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cCardIDAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCardIDEStringParserRuleCall_2_0 = (RuleCall)cCardIDAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cBalanceKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cBalanceAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cBalanceEStringParserRuleCall_4_1_0 = (RuleCall)cBalanceAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCatalogKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cCatalogAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cCatalogCardCatalogEnumRuleCall_5_1_0 = (RuleCall)cCatalogAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPasswordKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPasswordAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPasswordEStringParserRuleCall_6_1_0 = (RuleCall)cPasswordAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCard2bankKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cCard2bankAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cCard2bankBankCrossReference_7_1_0 = (CrossReference)cCard2bankAssignment_7_1.eContents().get(0);
		private final RuleCall cCard2bankBankEStringParserRuleCall_7_1_0_1 = (RuleCall)cCard2bankBankCrossReference_7_1_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cBc2customerKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cBc2customerAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cBc2customerCustomerCrossReference_8_1_0 = (CrossReference)cBc2customerAssignment_8_1.eContents().get(0);
		private final RuleCall cBc2customerCustomerEStringParserRuleCall_8_1_0_1 = (RuleCall)cBc2customerCustomerCrossReference_8_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//BankCard returns BankCard:
		//    {BankCard}
		//    'BankCard'
		//    cardID=EString
		//    '{'
		//        ('balance' balance=EString)?
		//        ('catalog' catalog=CardCatalog)?
		//        ('password' password=EString)?
		//        ('card2bank' card2bank=[Bank|EString])?
		//        ('bc2customer' bc2customer=[Customer|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{BankCard}
		//'BankCard'
		//cardID=EString
		//'{'
		//    ('balance' balance=EString)?
		//    ('catalog' catalog=CardCatalog)?
		//    ('password' password=EString)?
		//    ('card2bank' card2bank=[Bank|EString])?
		//    ('bc2customer' bc2customer=[Customer|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{BankCard}
		public Action getBankCardAction_0() { return cBankCardAction_0; }
		
		//'BankCard'
		public Keyword getBankCardKeyword_1() { return cBankCardKeyword_1; }
		
		//cardID=EString
		public Assignment getCardIDAssignment_2() { return cCardIDAssignment_2; }
		
		//EString
		public RuleCall getCardIDEStringParserRuleCall_2_0() { return cCardIDEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('balance' balance=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'balance'
		public Keyword getBalanceKeyword_4_0() { return cBalanceKeyword_4_0; }
		
		//balance=EString
		public Assignment getBalanceAssignment_4_1() { return cBalanceAssignment_4_1; }
		
		//EString
		public RuleCall getBalanceEStringParserRuleCall_4_1_0() { return cBalanceEStringParserRuleCall_4_1_0; }
		
		//('catalog' catalog=CardCatalog)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'catalog'
		public Keyword getCatalogKeyword_5_0() { return cCatalogKeyword_5_0; }
		
		//catalog=CardCatalog
		public Assignment getCatalogAssignment_5_1() { return cCatalogAssignment_5_1; }
		
		//CardCatalog
		public RuleCall getCatalogCardCatalogEnumRuleCall_5_1_0() { return cCatalogCardCatalogEnumRuleCall_5_1_0; }
		
		//('password' password=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'password'
		public Keyword getPasswordKeyword_6_0() { return cPasswordKeyword_6_0; }
		
		//password=EString
		public Assignment getPasswordAssignment_6_1() { return cPasswordAssignment_6_1; }
		
		//EString
		public RuleCall getPasswordEStringParserRuleCall_6_1_0() { return cPasswordEStringParserRuleCall_6_1_0; }
		
		//('card2bank' card2bank=[Bank|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'card2bank'
		public Keyword getCard2bankKeyword_7_0() { return cCard2bankKeyword_7_0; }
		
		//card2bank=[Bank|EString]
		public Assignment getCard2bankAssignment_7_1() { return cCard2bankAssignment_7_1; }
		
		//[Bank|EString]
		public CrossReference getCard2bankBankCrossReference_7_1_0() { return cCard2bankBankCrossReference_7_1_0; }
		
		//EString
		public RuleCall getCard2bankBankEStringParserRuleCall_7_1_0_1() { return cCard2bankBankEStringParserRuleCall_7_1_0_1; }
		
		//('bc2customer' bc2customer=[Customer|EString])?
		public Group getGroup_8() { return cGroup_8; }
		
		//'bc2customer'
		public Keyword getBc2customerKeyword_8_0() { return cBc2customerKeyword_8_0; }
		
		//bc2customer=[Customer|EString]
		public Assignment getBc2customerAssignment_8_1() { return cBc2customerAssignment_8_1; }
		
		//[Customer|EString]
		public CrossReference getBc2customerCustomerCrossReference_8_1_0() { return cBc2customerCustomerCrossReference_8_1_0; }
		
		//EString
		public RuleCall getBc2customerCustomerEStringParserRuleCall_8_1_0_1() { return cBc2customerCustomerEStringParserRuleCall_8_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class BankElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.atm.Dsl.Bank");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBankKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cBankNameKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cBankNameAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cBankNameEStringParserRuleCall_2_1_0 = (RuleCall)cBankNameAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAddressKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cAddressAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cAddressEStringParserRuleCall_3_1_0 = (RuleCall)cAddressAssignment_3_1.eContents().get(0);
		private final Keyword cAtmFromKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cAtmFromAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cAtmFromATMParserRuleCall_6_0 = (RuleCall)cAtmFromAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cAtmFromAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cAtmFromATMParserRuleCall_7_1_0 = (RuleCall)cAtmFromAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Bank returns Bank:
		//    'Bank'
		//    '{'
		//        ('bankName' bankName=EString)?
		//        ('address' address=EString)?
		//        'atmFrom' '{' atmFrom+=ATM ( "," atmFrom+=ATM)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Bank'
		//'{'
		//    ('bankName' bankName=EString)?
		//    ('address' address=EString)?
		//    'atmFrom' '{' atmFrom+=ATM ( "," atmFrom+=ATM)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Bank'
		public Keyword getBankKeyword_0() { return cBankKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('bankName' bankName=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'bankName'
		public Keyword getBankNameKeyword_2_0() { return cBankNameKeyword_2_0; }
		
		//bankName=EString
		public Assignment getBankNameAssignment_2_1() { return cBankNameAssignment_2_1; }
		
		//EString
		public RuleCall getBankNameEStringParserRuleCall_2_1_0() { return cBankNameEStringParserRuleCall_2_1_0; }
		
		//('address' address=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'address'
		public Keyword getAddressKeyword_3_0() { return cAddressKeyword_3_0; }
		
		//address=EString
		public Assignment getAddressAssignment_3_1() { return cAddressAssignment_3_1; }
		
		//EString
		public RuleCall getAddressEStringParserRuleCall_3_1_0() { return cAddressEStringParserRuleCall_3_1_0; }
		
		//'atmFrom'
		public Keyword getAtmFromKeyword_4() { return cAtmFromKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//atmFrom+=ATM
		public Assignment getAtmFromAssignment_6() { return cAtmFromAssignment_6; }
		
		//ATM
		public RuleCall getAtmFromATMParserRuleCall_6_0() { return cAtmFromATMParserRuleCall_6_0; }
		
		//( "," atmFrom+=ATM)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//atmFrom+=ATM
		public Assignment getAtmFromAssignment_7_1() { return cAtmFromAssignment_7_1; }
		
		//ATM
		public RuleCall getAtmFromATMParserRuleCall_7_1_0() { return cAtmFromATMParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class ReceiptElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.atm.Dsl.Receipt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cReceiptAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cReceiptKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTimeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTimeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTimeEStringParserRuleCall_3_1_0 = (RuleCall)cTimeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOperationNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOperationNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cOperationNameEStringParserRuleCall_4_1_0 = (RuleCall)cOperationNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cBalanceChangedKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cBalanceChangedAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cBalanceChangedEStringParserRuleCall_5_1_0 = (RuleCall)cBalanceChangedAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cBalanceRemainKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cBalanceRemainAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cBalanceRemainEStringParserRuleCall_6_1_0 = (RuleCall)cBalanceRemainAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cBankKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cBankAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cBankBankCrossReference_7_1_0 = (CrossReference)cBankAssignment_7_1.eContents().get(0);
		private final RuleCall cBankBankEStringParserRuleCall_7_1_0_1 = (RuleCall)cBankBankCrossReference_7_1_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cAtmKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cAtmAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cAtmATMCrossReference_8_1_0 = (CrossReference)cAtmAssignment_8_1.eContents().get(0);
		private final RuleCall cAtmATMEStringParserRuleCall_8_1_0_1 = (RuleCall)cAtmATMCrossReference_8_1_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cBankcardKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cBankcardAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cBankcardBankCardCrossReference_9_1_0 = (CrossReference)cBankcardAssignment_9_1.eContents().get(0);
		private final RuleCall cBankcardBankCardEStringParserRuleCall_9_1_0_1 = (RuleCall)cBankcardBankCardCrossReference_9_1_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cR2customerKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cR2customerAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cR2customerCustomerCrossReference_10_1_0 = (CrossReference)cR2customerAssignment_10_1.eContents().get(0);
		private final RuleCall cR2customerCustomerEStringParserRuleCall_10_1_0_1 = (RuleCall)cR2customerCustomerCrossReference_10_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Receipt returns Receipt:
		//    {Receipt}
		//    'Receipt'
		//    '{'
		//        ('time' time=EString)?
		//        ('operationName' operationName=EString)?
		//        ('balanceChanged' balanceChanged=EString)?
		//        ('balanceRemain' balanceRemain=EString)?
		//        ('bank' bank=[Bank|EString])?
		//        ('atm' atm=[ATM|EString])?
		//        ('bankcard' bankcard=[BankCard|EString])?
		//        ('r2customer' r2customer=[Customer|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Receipt}
		//'Receipt'
		//'{'
		//    ('time' time=EString)?
		//    ('operationName' operationName=EString)?
		//    ('balanceChanged' balanceChanged=EString)?
		//    ('balanceRemain' balanceRemain=EString)?
		//    ('bank' bank=[Bank|EString])?
		//    ('atm' atm=[ATM|EString])?
		//    ('bankcard' bankcard=[BankCard|EString])?
		//    ('r2customer' r2customer=[Customer|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Receipt}
		public Action getReceiptAction_0() { return cReceiptAction_0; }
		
		//'Receipt'
		public Keyword getReceiptKeyword_1() { return cReceiptKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('time' time=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'time'
		public Keyword getTimeKeyword_3_0() { return cTimeKeyword_3_0; }
		
		//time=EString
		public Assignment getTimeAssignment_3_1() { return cTimeAssignment_3_1; }
		
		//EString
		public RuleCall getTimeEStringParserRuleCall_3_1_0() { return cTimeEStringParserRuleCall_3_1_0; }
		
		//('operationName' operationName=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'operationName'
		public Keyword getOperationNameKeyword_4_0() { return cOperationNameKeyword_4_0; }
		
		//operationName=EString
		public Assignment getOperationNameAssignment_4_1() { return cOperationNameAssignment_4_1; }
		
		//EString
		public RuleCall getOperationNameEStringParserRuleCall_4_1_0() { return cOperationNameEStringParserRuleCall_4_1_0; }
		
		//('balanceChanged' balanceChanged=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'balanceChanged'
		public Keyword getBalanceChangedKeyword_5_0() { return cBalanceChangedKeyword_5_0; }
		
		//balanceChanged=EString
		public Assignment getBalanceChangedAssignment_5_1() { return cBalanceChangedAssignment_5_1; }
		
		//EString
		public RuleCall getBalanceChangedEStringParserRuleCall_5_1_0() { return cBalanceChangedEStringParserRuleCall_5_1_0; }
		
		//('balanceRemain' balanceRemain=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'balanceRemain'
		public Keyword getBalanceRemainKeyword_6_0() { return cBalanceRemainKeyword_6_0; }
		
		//balanceRemain=EString
		public Assignment getBalanceRemainAssignment_6_1() { return cBalanceRemainAssignment_6_1; }
		
		//EString
		public RuleCall getBalanceRemainEStringParserRuleCall_6_1_0() { return cBalanceRemainEStringParserRuleCall_6_1_0; }
		
		//('bank' bank=[Bank|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'bank'
		public Keyword getBankKeyword_7_0() { return cBankKeyword_7_0; }
		
		//bank=[Bank|EString]
		public Assignment getBankAssignment_7_1() { return cBankAssignment_7_1; }
		
		//[Bank|EString]
		public CrossReference getBankBankCrossReference_7_1_0() { return cBankBankCrossReference_7_1_0; }
		
		//EString
		public RuleCall getBankBankEStringParserRuleCall_7_1_0_1() { return cBankBankEStringParserRuleCall_7_1_0_1; }
		
		//('atm' atm=[ATM|EString])?
		public Group getGroup_8() { return cGroup_8; }
		
		//'atm'
		public Keyword getAtmKeyword_8_0() { return cAtmKeyword_8_0; }
		
		//atm=[ATM|EString]
		public Assignment getAtmAssignment_8_1() { return cAtmAssignment_8_1; }
		
		//[ATM|EString]
		public CrossReference getAtmATMCrossReference_8_1_0() { return cAtmATMCrossReference_8_1_0; }
		
		//EString
		public RuleCall getAtmATMEStringParserRuleCall_8_1_0_1() { return cAtmATMEStringParserRuleCall_8_1_0_1; }
		
		//('bankcard' bankcard=[BankCard|EString])?
		public Group getGroup_9() { return cGroup_9; }
		
		//'bankcard'
		public Keyword getBankcardKeyword_9_0() { return cBankcardKeyword_9_0; }
		
		//bankcard=[BankCard|EString]
		public Assignment getBankcardAssignment_9_1() { return cBankcardAssignment_9_1; }
		
		//[BankCard|EString]
		public CrossReference getBankcardBankCardCrossReference_9_1_0() { return cBankcardBankCardCrossReference_9_1_0; }
		
		//EString
		public RuleCall getBankcardBankCardEStringParserRuleCall_9_1_0_1() { return cBankcardBankCardEStringParserRuleCall_9_1_0_1; }
		
		//('r2customer' r2customer=[Customer|EString])?
		public Group getGroup_10() { return cGroup_10; }
		
		//'r2customer'
		public Keyword getR2customerKeyword_10_0() { return cR2customerKeyword_10_0; }
		
		//r2customer=[Customer|EString]
		public Assignment getR2customerAssignment_10_1() { return cR2customerAssignment_10_1; }
		
		//[Customer|EString]
		public CrossReference getR2customerCustomerCrossReference_10_1_0() { return cR2customerCustomerCrossReference_10_1_0; }
		
		//EString
		public RuleCall getR2customerCustomerEStringParserRuleCall_10_1_0_1() { return cR2customerCustomerEStringParserRuleCall_10_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	
	public class CardCatalogElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.atm.Dsl.CardCatalog");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCREDITEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCREDITCREDITKeyword_0_0 = (Keyword)cCREDITEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDEBITEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDEBITDEBITKeyword_1_0 = (Keyword)cDEBITEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum CardCatalog returns CardCatalog:
		//                CREDIT = 'CREDIT' | DEBIT = 'DEBIT';
		public EnumRule getRule() { return rule; }
		
		//CREDIT = 'CREDIT' | DEBIT = 'DEBIT'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CREDIT = 'CREDIT'
		public EnumLiteralDeclaration getCREDITEnumLiteralDeclaration_0() { return cCREDITEnumLiteralDeclaration_0; }
		
		//'CREDIT'
		public Keyword getCREDITCREDITKeyword_0_0() { return cCREDITCREDITKeyword_0_0; }
		
		//DEBIT = 'DEBIT'
		public EnumLiteralDeclaration getDEBITEnumLiteralDeclaration_1() { return cDEBITEnumLiteralDeclaration_1; }
		
		//'DEBIT'
		public Keyword getDEBITDEBITKeyword_1_0() { return cDEBITDEBITKeyword_1_0; }
	}
	
	private final ATMElements pATM;
	private final EStringElements pEString;
	private final BankClerkElements pBankClerk;
	private final CustomerElements pCustomer;
	private final BankCardElements pBankCard;
	private final BankElements pBank;
	private final ReceiptElements pReceipt;
	private final CardCatalogElements eCardCatalog;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pATM = new ATMElements();
		this.pEString = new EStringElements();
		this.pBankClerk = new BankClerkElements();
		this.pCustomer = new CustomerElements();
		this.pBankCard = new BankCardElements();
		this.pBank = new BankElements();
		this.pReceipt = new ReceiptElements();
		this.eCardCatalog = new CardCatalogElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.rm2pt.sample.atm.Dsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//ATM returns ATM:
	//    {ATM}
	//    'ATM'
	//    '{'
	//        ('atmID' atmID=EString)?
	//        ('address' address=EString)?
	//    '}';
	public ATMElements getATMAccess() {
		return pATM;
	}
	
	public ParserRule getATMRule() {
		return getATMAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//BankClerk returns BankClerk:
	//    {BankClerk}
	//    'BankClerk'
	//    userID=EString
	//    '{'
	//        ('name' name=EString)?
	//        ('address' address=EString)?
	//        ('age' age=EString)?
	//        ('phone' phone=EString)?
	//        ('Post' Post=EString)?
	//        ('pin' pin=EString)?
	//        ('uesr2bank' uesr2bank=[Bank|EString])?
	//        ('atmUser' atmUser=[ATM|EString])?
	//    '}';
	public BankClerkElements getBankClerkAccess() {
		return pBankClerk;
	}
	
	public ParserRule getBankClerkRule() {
		return getBankClerkAccess().getRule();
	}
	
	//Customer returns Customer:
	//    {Customer}
	//    'Customer'
	//    userID=EString
	//    '{'
	//        ('name' name=EString)?
	//        ('address' address=EString)?
	//        ('age' age=EString)?
	//        ('phone' phone=EString)?
	//        ('uesr2bank' uesr2bank=[Bank|EString])?
	//        ('atmUser' atmUser=[ATM|EString])?
	//    '}';
	public CustomerElements getCustomerAccess() {
		return pCustomer;
	}
	
	public ParserRule getCustomerRule() {
		return getCustomerAccess().getRule();
	}
	
	//BankCard returns BankCard:
	//    {BankCard}
	//    'BankCard'
	//    cardID=EString
	//    '{'
	//        ('balance' balance=EString)?
	//        ('catalog' catalog=CardCatalog)?
	//        ('password' password=EString)?
	//        ('card2bank' card2bank=[Bank|EString])?
	//        ('bc2customer' bc2customer=[Customer|EString])?
	//    '}';
	public BankCardElements getBankCardAccess() {
		return pBankCard;
	}
	
	public ParserRule getBankCardRule() {
		return getBankCardAccess().getRule();
	}
	
	//Bank returns Bank:
	//    'Bank'
	//    '{'
	//        ('bankName' bankName=EString)?
	//        ('address' address=EString)?
	//        'atmFrom' '{' atmFrom+=ATM ( "," atmFrom+=ATM)* '}'
	//    '}';
	public BankElements getBankAccess() {
		return pBank;
	}
	
	public ParserRule getBankRule() {
		return getBankAccess().getRule();
	}
	
	//Receipt returns Receipt:
	//    {Receipt}
	//    'Receipt'
	//    '{'
	//        ('time' time=EString)?
	//        ('operationName' operationName=EString)?
	//        ('balanceChanged' balanceChanged=EString)?
	//        ('balanceRemain' balanceRemain=EString)?
	//        ('bank' bank=[Bank|EString])?
	//        ('atm' atm=[ATM|EString])?
	//        ('bankcard' bankcard=[BankCard|EString])?
	//        ('r2customer' r2customer=[Customer|EString])?
	//    '}';
	public ReceiptElements getReceiptAccess() {
		return pReceipt;
	}
	
	public ParserRule getReceiptRule() {
		return getReceiptAccess().getRule();
	}
	
	//enum CardCatalog returns CardCatalog:
	//                CREDIT = 'CREDIT' | DEBIT = 'DEBIT';
	public CardCatalogElements getCardCatalogAccess() {
		return eCardCatalog;
	}
	
	public EnumRule getCardCatalogRule() {
		return getCardCatalogAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
